openapi: 3.0.0
info:
  title: Pet Tracking API
  version: 1.0.0
paths:
  /pets:
    get:
      summary: List all pets
      operationId: listPets
      responses:
        '200':
          description: A list of pets.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ApiPet'
    post:
      summary: Create a pet
      operationId: createPet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiPet'
      responses:
        '201':
          description: Pet created
  /pets/count:
    get:
      summary: Count pets by category
      operationId: countPets
      parameters:
        - name: inZone
          in: query
          description: If the pet is in the power saving zone
          required: false
          schema:
            type: boolean
      responses:
        '200':
          description: A count of pets.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PetCount'

components:
  schemas:
    ApiPet:
      required:
        - petType
        - ownerId
      properties:
        petType:
          type: string
          enum: [Cat, Dog]
        ownerId:
          description: The owner's ID
          type: integer
          format: int64
        trackerType:
          description: Type of tracker, only dogs can have medium
          type: string
          enum: [ small, medium, big ]
        inZone:
          description: If the pet is in the power saving zone
          type: boolean
        lostTracker:
          description: If the tracker is lost, only for cats
          type: boolean

    PetCount:
      properties:
        count:
          type: integer
          format: int64
        dogs:
          type: integer
          format: int64
        cats:
          type: integer
          format: int64




